spring.application.name=mantenimiento

spring.datasource.url=jdbc:mysql://metro.proxy.rlwy.net:43319/railway
spring.datasource.username=root
spring.datasource.password=TfLYrHuZFOsKnPRXfKOrDlFiwOAkfErC

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect